// Stage 4 mobile entry point. Wires:
//   - biometric + keystore commands from `auth.rs` (Stage 3)
//   - encrypted vault file commands from `vault.rs` (Stage 4 prep)
//   - deep-link plugin (Stage 4 — `monolythium://` and `lyth:` schemes)
//   - tauri-plugin-store (Stage 4 — WalletConnect v2 session persistence)
//   - tauri-plugin-notification — native OS notifications for confirmed/
//     failed txs, additive to the in-app notifications center; any-target
//     like deep-link + store. The JS side requests permission on first use.
//
// The deep-link plugin is registered on every target (desktop + iOS +
// Android) — desktop registration is needed for both the `tauri ios dev`
// macOS host that proxies URL schemes back to the simulator AND for
// developer testing without a phone. The on-open-url callback fires the
// `mw:deep-link` event with the raw URL list. The frontend (`src/sdk/
// deeplink.ts`) parses scheme + payload and routes to the right surface
// (Send / Sign / WC pairing).
//
// `tauri-plugin-store` is also any-target — the WC v2 session topic +
// peer metadata + accounts + expiry persists in `wc-sessions.v1.json`
// next to the vault, owned by the JS `wcStore` wrapper.

mod auth;
mod vault;

use tauri::Emitter;
use tauri_plugin_deep_link::DeepLinkExt;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = tauri::Builder::default()
        .plugin(tauri_plugin_deep_link::init())
        .plugin(tauri_plugin_store::Builder::new().build())
        .plugin(tauri_plugin_notification::init())
        .invoke_handler(tauri::generate_handler![
            auth::biometric_is_available,
            auth::biometric_authenticate,
            auth::keychain_has,
            auth::keychain_set,
            auth::keychain_get,
            auth::keychain_delete,
            vault::vault_exists,
            vault::vault_read,
            vault::vault_write,
            vault::vault_delete,
        ]);

    let builder = configure_mobile_plugins(builder);

    builder
        .setup(|app| {
            // On desktop hosts, register the URL schemes at runtime so the
            // OS can route `monolythium://...` and `lyth:...` to a running
            // instance. On iOS / Android the schemes come from the bundle
            // manifest (Info.plist URL types / AndroidManifest intent-filter)
            // — generated by tauri-plugin-deep-link from `tauri.conf.json`.
            // `register_all` is a no-op on platforms that don't need it.
            #[cfg(any(
                target_os = "linux",
                all(debug_assertions, windows),
                target_os = "macos"
            ))]
            {
                if let Err(e) = app.deep_link().register_all() {
                    eprintln!("deep-link register_all failed: {e}");
                }
            }

            // Forward every incoming URL to the React layer.
            // `urls` is a Vec<Url>; we serialise to strings and let the
            // frontend dispatch on scheme + path.
            let handle = app.handle().clone();
            app.deep_link().on_open_url(move |event| {
                let urls: Vec<String> =
                    event.urls().iter().map(|u| u.to_string()).collect();
                if let Err(e) = handle.emit("mw:deep-link", &urls) {
                    eprintln!("emit mw:deep-link failed: {e}");
                }
            });

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running Monolythium Wallet Mobile");
}

#[cfg(any(target_os = "ios", target_os = "android"))]
fn configure_mobile_plugins(builder: tauri::Builder<tauri::Wry>) -> tauri::Builder<tauri::Wry> {
    builder
        .plugin(tauri_plugin_biometric::init())
        .plugin(tauri_plugin_keystore::init())
}

#[cfg(not(any(target_os = "ios", target_os = "android")))]
fn configure_mobile_plugins(builder: tauri::Builder<tauri::Wry>) -> tauri::Builder<tauri::Wry> {
    // Desktop host build — biometric/keystore plugins aren't linked. The
    // `auth::*` commands return `AuthError::Unavailable` and the frontend
    // falls back to its password path. Deep-link + store ARE linked on
    // desktop (registered in `run()` directly), so no fallback needed.
    builder
}
